<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid ">
            <div class="cssUserImage span2">
                <img name="avatar" src="<?= $this->baseUrl() ?>/img/dummy_domain_200.png" alt="<?= $this->translate('avatar') ?>">
            </div>
            <form id="formStorage" class="span10" method="post" 
                  action="<?= $this->url(array(), 'mazelab-storage_add') ?>" >
                <dl class="row-fluid">
                    <dt class="span3">
                        <label>
                            <?= $this->translate('Name') ?>
                        </label>
                    </dt>
                    <dd class="span9">
                        <?= $this->form->name ?>
                    </dd>
                </dl>
                
                <dl class="row-fluid">
                    <dt class="span3">
                        <label>
                            <?= $this->translate('Client') ?>
                        </label>
                    </dt>
                    <dd class="span9">
                        <?= $this->form->clientId ?>
                    </dd>
                </dl>
                
                <dl class="row-fluid">
                    <dt class="span3">
                        <label>
                            <?= $this->translate('Quota in MB') ?>
                        </label>
                    </dt>
                    <dd class="span9">
                        <?= $this->form->quota ?>
                    </dd>
                </dl>
                
                <dl class="row-fluid">
                    <dt class="span3">
                        <label>
                            <?= $this->translate('Node') ?>
                        </label>
                    </dt>
                    <dd class="span9">
                        <?= $this->form->nodeId ?>
                    </dd>
                </dl>

                <dl class="row-fluid">
                    <dt class="span3">
                        <label>
                            <?= $this->translate('Storage is') ?>
                        </label>
                    </dt>
                    <dd class="span9">
                        <?= $this->form->status ?>
                    </dd>
                </dl>
                
                <dl class="row-fluid">
                    <dt class="span3">
                        <label>
                            <?= $this->translate('Password') ?>
                        </label>
                    </dt>
                    <dd class="span9">
                        <?= $this->form->password ?>
                    </dd>
                </dl>
                
                <dl class="row-fluid">
                    <dt class="span3">
                        <label>
                            <?= $this->translate('Confirm Password') ?>
                        </label>
                    </dt>
                    <dd class="span9">
                        <?= $this->form->confirmPassword ?>
                    </dd>
                </dl>

                <div class="row-fluid">
                    <a id="cancel" class="btn btn-info"
                       title="<?= $this->translate('Cancel') ?>">
                        <?= $this->translate('Cancel') ?>
                    </a>
                    <a id="save" class="btn btn-info"
                       title="<?= $this->translate('Save') ?>">
                        <?= $this->translate('Save') ?>
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#cancel').click(function() {
            location.href = '<?= $this->url(array(), 'mazelab-storage_index'); ?>';
        });
        
        $('#save').click(function() {
            $('#formStorage').submit();
        });
    });
</script>