<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid text-left cssBoxCenter">
            <div class="span6">
                <div class="row-fluid">
                    <h4>
                        Maze
                    </h4>
                </div>

                <form id="formLocal" name="local" method="POST"
                      action="<?= $this->url(array($this->html('storage/_id')), 'mazelab-storage_edit') ?>?format=json">
                    <div class="row-fluid">
                        <dt class="span3">
                            <label>
                                <?= $this->translate('Status') ?>
                            </label>
                        </dt>
                        <dd class="span6">
                            <?= $this->form->local->status ?>
                        </dd>
                    </div>

                    <div class="row-fluid">
                        <dt class="span3">
                            <label>
                                <?= $this->translate('Quota') ?>
                            </label>
                        </dt>
                        <dd class="span6">
                            <?= $this->form->local->quota ?>
                        </dd>
                    </div>

                    <div class="row-fluid">
                        <input class="btn btn-info jsButtonApply"
                        type="submit" value="<?= $this->translate('Apply'); ?>">
                    </div>
                </form>
            </div>

            <div class="span6">
                <div class="row-fluid">
                    <h4>
                        Node
                    </h4>
                </div>

                <form id="formRemote" name="remote" method="POST"
                      action="<?= $this->url(array($this->html('storage/_id')), 'mazelab-storage_edit') ?>?format=json">
                    <div class="row-fluid">
                        <dt class="span3">
                            <label>
                                <?= $this->translate('Status') ?>
                            </label>
                        </dt>
                        <dd class="span6">
                            <?= $this->form->remote->status ?>
                        </dd>
                    </div>

                    <div class="row-fluid">
                        <dt class="span3">
                            <label>
                                <?= $this->translate('Quota') ?>
                            </label>
                        </dt>
                        <dd class="span6">
                            <?= $this->form->remote->quota ?>
                        </dd>
                    </div>

                    <div class="row-fluid">
                        <input class="btn btn-info jsButtonApply" type="submit"
                               value="<?= $this->translate('Apply'); ?>">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#formLocal, #formRemote').submit(function() {
            resetAllMessages();
            var self = $(this);
            $('.jsButtonApply').addClass('disabled');

            !self.data("locked") && $.ajax({
                type: 'POST',
                url: self.attr('action'),
                data: self.serialize(),
                success:function(data){
                    if(data.result === true) {
                        location.reload();
                    } else if(data.errors && data.errors[self.attr('name')]) {
                        for(var error in data.errors[self.attr('name')]){
                            var selector = '#' + self.attr('name') + '-' + error;
                            var messages = data.errors[self.attr('name')][error];

                            setErrorTooltip(messages, selector);
                        }
                    } else {
                        setErrorMessages(['<?= $this->translate('Request failed') ?>']);
                    }
                },
                error: function() {
                    setErrorMessages(['<?= $this->translate('Request failed') ?>']);
                },
                complete:function(){
                    $('.jsButtonApply').removeClass('disabled');
                    self.data("locked", false);
                }
            });
            self.data("locked", true);

            return false;
        });
    });
</script>
