<div class="cssContentMiddle grid_16">
    <h1 class="grid_16">
        <?= $this->translate('All Storages client %1$s', $this->html("identity/label")); ?>
    </h1>
    
    <?= $this->render('storage/searchfield.phtml') ?>
    
    <div class="cssListing grid_16">
        <div class="grid_16 alpha omega cssHeaderList">
            <div class="grid_16 alpha omega cssAction">
                <h3><?= $this->translate('actions') ?></h3>
            </div>
        </div>
        
        <ul id="pagerContent" class="span12 unstyled">
            <?= $this->render('storage/indexclient.ajax.phtml') ?>
        </ul>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#searchInput').mazeSearch('option', 'source', "<?= $this->url(array(), 'mazelab-storage_index') ?>?format=html");
    });
</script>